// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/caos-themes/GlassDark.tsx": () => import("../components/mockups/caos-themes/GlassDark.tsx"),
  "./components/mockups/caos-themes/Holographic.tsx": () => import("../components/mockups/caos-themes/Holographic.tsx"),
  "./components/mockups/caos-themes/Monolith.tsx": () => import("../components/mockups/caos-themes/Monolith.tsx")
};
